# Generated by Django 3.2 on 2023-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galetosapp', '0004_neworder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='neworder',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
