# Generated by Django 3.2 on 2023-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galetosapp', '0005_auto_20231025_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
